version: '3.9'
services:
  frontend:
    container_name: praisepal-frontend
    image: biggiefrye45/praisepal-frontend:latest
    env_file:
      - .env
    networks:
      ipv4_address: '10.55.1.252'
    ports:
      - 80:80
