version: '3.9'
services:
  frontend:
    container_name: praisepal-frontend
    image: biggiefrye45/praisepal-frontend:latest
    env_file:
      - .env
    networks:
      - praisepal_default
    ports:
      - 8012:80
    resources:
      limits:
        cpus: '0.5'
        memory: 512M
    restart: unless-stopped

networks:
  praisepal_default:
    external: true
