version: '3.9'
services:
  frontend:
    container_name: praisepal-frontend
    image: biggiefrye45/praisepal-frontend:staging
    env_file:
      - .env
    networks:
      - praisepal_default
    ports:
      - 8011:80
    volumes:
      - ./docker/frontend:/app #comment this line for production
      # -/docker/appdata/praisepal/frontend:/app #uncomment this line for production

networks:
  praisepal_default:
    external: true
