version: '3.9'
services:
  frontend:
    container_name: praisepal-frontend-staging
    image: biggiefrye45/praisepal-frontend:staging
    env_file:
      - .env
    networks:
      - praisepal_staging
    ports:
      - 8013:80

networks:
  praisepal_staging:
    external: true
