version: '3.9'
services:
  frontend:
    container_name: praisepal-frontend
    image: biggiefrye45/praisepal-frontend:latest
    env_file:
      - .env
    networks:
      - praisepal_default
    ports:
      - 8012:80

networks:
  praisepal_default:
    external: true
