version: '3.9'

services:
  db:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: praisepal
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data:rw
    networks:
      - praisepal_default

  backend:
    container_name: praisepal-backend
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./backend/.env
    networks:
      - praisepal_default
    ports:
      - 3001:3001
    volumes:
      - ./docker/backend:/app
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - tag=biggiefrye45/praisepal-backend:staging

  frontend:
    container_name: praisepal-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - praisepal_default
    ports:
      - 8012:80
    volumes:
      - ./frontend:/app
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:3001
        - tag=biggiefrye45/praisepal-frontend:staging

networks:
  praisepal_default:
    external: true

volumes:
  data:
  backend:
