version: '3.9'

services:
  db:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: praisepal
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data:rw
    networks:
      - nginx

networks:
  nginx:
    external: true

volumes:
  data:
