version: '3.9'

services:
  backend:
    container_name: praisepal-backend
    image: biggiefrye45/praisepal-backend:staging
    env_file:
      - .env
    networks:
      - praisepal_default
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app
    restart: unless-stopped

networks:
  praisepal_default:
    external: true
