services:
  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    networks:
      ipv4_address: '10.56.1.250'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: praisepal
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
