---
services:
  backend:
    container_name: praisepal-backend
    image: biggiefrye45/praisepal-backend:latest
    env_file:
      - .env
    networks:
      ipv4_address: '10.56.1.251'
    ports:
      - 3001:3001
    volumes:
      - /docker/appdata/praisepal/backend:/app
    restart: unless-stopped
